"""
Django settings for barberstein project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os 
import django_mongodb_backend

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kd1%q%ppbdgox_w!(d)0uya4p3rxkt+6q^tcby&qng#m79=^uj'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
#ALLOWED_HOSTS = ['apibarberia.vercel.app']

DEBUG = True
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'barberstein.apps.MongoAdminConfig',
    'barberstein.apps.MongoAuthConfig',
    'barberstein.apps.MongoContentTypesConfig',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'djoser',
    'rest_framework',
    'rest_framework_simplejwt', 
    'rest_framework.authtoken',
    'drf_spectacular', #django spectacular sirve como documentacion de swagger
    'corsheaders',
    'pwa'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir antes de cualquier middleware que maneje solicitudes
    #'barberstein.middleware.BlockPostmanMiddleware',
    #'barberstein.middleware.CustomHeaderMiddleware', 
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'barberstein.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barberstein.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": django_mongodb_backend.parse_uri("mongodb+srv://jesusmedina0921:rtYRvTorUpIDCqDz@cluster0.xvyzd3u.mongodb.net/Barberia?retryWrites=true&w=majority&appName=Cluster0"),
}

# Database routers
# https://docs.djangoproject.com/en/dev/ref/settings/#database-routers
DATABASE_ROUTERS = ["django_mongodb_backend.routers.MongoRouter"]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
#Codigo para definir el formato de numeros. Ejemplo 100.000,00 (formato europeo/latinoamericano) o 100,000.00 (formato anglosajón),
USE_L10N = True  # Asegúrate que esté en True
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Define la ruta para MEDIA_ROOT

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'build')  # Define la ruta para STATIC_ROOT

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

MIGRATION_MODULES = {
    'admin': 'mongo_migrations.admin',
    'auth': 'mongo_migrations.auth',
    'contenttypes': 'mongo_migrations.contenttypes',
}

#Aqui indico y permito que URL pueda accedar a la api
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://Barberstein.vercel.app", # Web Produccion
    "https://localhost",              # App movil
    "http://localhost:8100",          # Desarrollo Frontend
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Barberstein-Secret'  # Header personalizado
]


CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Validacion para que solo los urls del CORS consuman la api en produccion
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

SECURE_API_HEADER = 'Barberstein-Secret'  
SECURE_API_VALUE = '354def87618f85957317f83c62ee9f871bf8b5cd66ad911101db5efd68d71a94'  # DEBE SER EL MISMO QUE EN ANGULAR

AUTH_USER_MODEL = 'api.User'


REST_FRAMEWORK = {

    #Paginacion
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, # Esto define el número predeterminado de elementos por página
   

    #DRF JWT
       'DEFAULT_AUTHENTICATION_CLASSES': (
           'rest_framework_simplejwt.authentication.JWTAuthentication',
       ),

    #PERMISOS
       'DEFAULT_PERMISSION_CLASS': ('rest_framework.permissions.IsAuthenticated',),
    #DRF SPECTACULAR
       'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
  
   }

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('JWT',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    #Tiempo de expiracion del TOKEN

    #PARA DESARROLLO ESTA CONFIGURACION

    # Tiempo de vida del token de acceso (default: 5 minutos)
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 hora
    ## Tiempo de vida del token de refresco (default: 1 día)
    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 1 semana

    #PARA PRODUCCION ESTA CONFIGURACION
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)

    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)
    # Tiempo de vida del token de refresco cuando se usa para renovar (default: None)
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Permite renovar el refresh token cada vez que se usa
    'ROTATE_REFRESH_TOKENS': True,
    
    # Invalida los refresh tokens después de usarlos
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Actualiza la última hora de inicio de sesión del usuario
    'UPDATE_LAST_LOGIN': True,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'jesusmedina0921@gmail.com'
EMAIL_HOST_PASSWORD = 'npvhqpyrpbnuiigb'
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = 'jesusmedina0921@gmail.com' 
DOMAIN = 'localhost:8100'
SITE_NAME = 'Barberstein' 
PROTOCOL = 'http'

DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'SET_USERNAME_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    # Aquí Djoser construirá la URL por mi, por eso no debo poner el dominio
    'PASSWORD_RESET_CONFIRM_URL': 'auth/reset/password/confirm/{uid}/{token}/',
    'USERNAME_RESET_CONFIRM_URL': 'auth/reset/email/confirm/{uid}/{token}/',
    'ACTIVATION_URL': 'activate/{uid}/{token}/',
    'SEND_ACTIVATION_EMAIL': True,
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'djoser.social.token.jwt.TokenStrategy',
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': ['https://barberstein.vercel.app/google', 'https://barberstein.vercel.app/facebook'],
    'SERIALIZERS': {
        'user_create': 'api.serializers.UserCreateSerializer',
        'user': 'api.serializers.UserCreateSerializer',
        'current_user': 'api.serializers.UserCreateSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
    },
    'EMAIL': {
        'activation': 'api.custom_email.ActivationEmail', #confirmar correo cuando registro usuario
        'password_reset': 'api.custom_email.CustomPasswordResetEmail', #solicitud para recuperar password olvidada
        'password_changed_confirmation': 'api.custom_email.CustomPasswordChangedConfirmationEmail', #enlace que abro para nueva password
        'username_reset': 'api.custom_email.CustomUsernameResetEmail', #solicitud para recuperar email olvidado
        'email_changed_confirmation': 'api.custom_email.CustomEmailChangedConfirmationEmail',  # 
    },
}
#Configuracion de Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'Barberstein',
    'DESCRIPTION': 'API REST utilizada como Backend para una Red Social de Barberias. Desarrollada en Django Rest, MongoDB, implementando JWT, envio de correos, y desplagada en Vercel',
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'Barberstein',
        'email': 'jesusmedina0921@gmail.com',
        #'url': 'https://Barberstein.vercel.app',
    },
    #Orden de los tags en Swagger
    'TAGS': [
        {'name': 'Login', 'description': 'Operaciones de autenticación'},
        {'name': 'Token', 'description': 'Operaciones relacionadas con los tokens JWT'},
        {'name': 'auth', 'description': 'Operaciones relacionadas con la recuperacion de email/password, autenticacion de cuentas etc...'},
        {'name': 'Clientes', 'description': 'Operaciones relacionadas con los clientes'},
        {'name': 'Barberias', 'description': 'Operaciones relacionadas con los barberos o barberias'},
        {'name': 'Comentarios', 'description': 'Operaciones relacionadas con los comentarios para barberos o barberias'},
        {'name': 'Turnos', 'description': 'Operaciones relacionadas con los turnos de las barberias'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
}


PWA_APP_NAME = 'Barberstein'
PWA_APP_DESCRIPTION = "Barberstein"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = "#1c4216"
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {'src': '/static/images/icons/icon-72x72.png', 'sizes': '72x72'},
    {'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'},
    {'src': '/static/images/icons/icon-128x128.png', 'sizes': '128x128'},
    {'src': '/static/images/icons/icon-144x144.png', 'sizes': '144x144'},
    {'src': '/static/images/icons/icon-152x152.png', 'sizes': '152x152'},
    {'src': '/static/images/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/images/icons/icon-384x384.png', 'sizes': '384x384'},
    {'src': '/static/images/icons/icon-512x512.png', 'sizes': '512x512'},
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es'