# Generated by Django 5.2.4 on 2025-08-25 00:13

import api.mixins
import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_imagen', models.ImageField(blank=True, null=True, storage=api.mixins.ProfileCloudinaryStorage(), upload_to='profile_images/')),
                ('ubicacion_coordenadas', models.JSONField(blank=True, default=None, null=True)),
                ('biometric', models.CharField(blank=True, max_length=255, null=True)),
                ('barberia', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            bases=(api.mixins.AutoCleanMongoMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El rating mínimo es 1.'), django.core.validators.MaxValueValidator(5, message='El rating máximo es 5.')])),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('imagen_urls', models.JSONField(default=list)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('ARS', 'Peso argentino'), ('BOB', 'Boliviano'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno'), ('COP', 'Peso colombiano'), ('CRC', 'Colón costarricense'), ('CUP', 'Peso cubano'), ('DOP', 'Peso dominicano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('GTQ', 'Quetzal guatemalteco'), ('GYD', 'Dólar guyanés'), ('HTG', 'Gourde haitiano'), ('HNL', 'Lempira hondureño'), ('MXN', 'Peso mexicano'), ('NIO', 'Córdoba nicaragüense'), ('PAB', 'Balboa panameño'), ('PYG', 'Guaraní paraguayo'), ('PEN', 'Sol peruano'), ('SRD', 'Dólar surinamés'), ('TTD', 'Dólar de Trinidad y Tobago'), ('UYU', 'Peso uruguayo'), ('VES', 'Bolívar venezolano')], max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
            bases=(api.mixins.AutoCleanMongoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El turno mínimo es 1.'), django.core.validators.MaxValueValidator(100, message='El turno máximo es 100.')])),
                ('fecha_turno', models.DateField()),
                ('estado', models.CharField(choices=[('R', 'Reservado'), ('C', 'Cancelado')], default='R', max_length=1)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_turno', 'turno'],
            },
        ),
    ]
