# Generated by Django 5.2.3 on 2025-08-04 20:54

import api.mixins
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('biometric', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('barberia', models.JSONField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            bases=(api.mixins.AutoCleanMongoMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El rating mínimo es 1.'), django.core.validators.MaxValueValidator(5, message='El rating máximo es 5.')])),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('barberia', models.ForeignKey(limit_choices_to={'barberia__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('barberia', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El turno mínimo es 1.'), django.core.validators.MaxValueValidator(100, message='El turno máximo es 100.')])),
                ('fecha_turno', models.DateField()),
                ('estado', models.CharField(choices=[('R', 'Reservado'), ('C', 'Cancelado')], max_length=1)),
                ('barberia', models.ForeignKey(limit_choices_to={'barberia__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='barberia_turno', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_turno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_turno', 'turno'],
                'unique_together': {('barberia', 'turno', 'fecha_turno')},
            },
        ),
    ]
