# Generated by Django 5.2.4 on 2025-08-25 00:13

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0001_initial'),
        ('social_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAuthProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario con Redes Sociales',
                'verbose_name_plural': 'Usuarios con Redes Sociales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.usersocialauth',),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Barberia',
            fields=[
            ],
            options={
                'verbose_name': 'Barberia',
                'verbose_name_plural': 'Barberias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='barberia',
            field=models.ForeignKey(limit_choices_to={'barberia__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='barberia',
            field=models.ForeignKey(limit_choices_to={'barberia__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='barberia_servicio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turnos',
            name='barberia',
            field=models.ForeignKey(limit_choices_to={'barberia__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='barberia_turno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turnos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_turno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('barberia', 'cliente')},
        ),
        migrations.AlterUniqueTogether(
            name='turnos',
            unique_together={('barberia', 'turno', 'fecha_turno')},
        ),
    ]
